### ISSUE TITLE
Export API Types

### ISSUE THREAD

**Issue by evelynhathaway** [rocketryjs/rocketry#4]
# Device Plugin Layer
# MIDI Plugin Layer
- [ ] `MidiLayerAPI`
- [ ] `MessageType`
- [ ] `MIDIOptions`
- [ ] `PortsType`

**Comment by ruohki** [comment]
Hey, if you need any stuff on how to access all sorts of launchpads you can have a look at my repo ruohki/lunchpad does support all launchpads (but the pro mk3) :)

**Comment by evelynhathaway** [comment]
Thank you @ruohki. My intentions with Rocketry has been a similar goal so this my be a helpful reference haha!

**Comment by ruohki** [comment]
There is also a python project i used as a reference dor some of the stuff

Evelyn Hathaway <notifications@github.com> schrieb am So. 21. Juni 2020 um
00:27:
